set dotenv-load

#
# VARIABLES
#

#
# EXPORTS
#

export ROOT_DIR := `pwd`

#
# HELPERS
#

default: help

# Print the available recipes
help:
    @just --justfile {{justfile()}} --list

lint:
    ruff format
    ruff check --fix
